version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./chroma-data:/app/data/chroma
    env_file:
      - .env
    restart: unless-stopped
