name: News Scraper Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy env file
        run: |
          cp .env.example .env

      - name: Run tests in Docker
        uses: isbang/compose-action@v1.5.1
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: |
            app

      - name: Run pytest with coverage
        run: |
          mkdir -p coverage
          docker compose run --rm -v $(pwd)/coverage:/app/coverage app pytest --cov=src --cov-report=xml:/app/coverage/coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        continue-on-error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: zeloras/news-parser